-- V29__uom.sql
-- Unit of Measure tables (Odoo: uom.uom, uom.category)

CREATE TABLE uom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    CONSTRAINT uk_uom_categories_name UNIQUE (name)
);

CREATE TABLE uoms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10),
    category_id BIGINT NOT NULL REFERENCES uom_categories(id),
    factor NUMERIC(15,6) NOT NULL DEFAULT 1,
    rounding NUMERIC(15,6),
    is_reference BOOLEAN NOT NULL DEFAULT FALSE,
    uom_type VARCHAR(20) NOT NULL DEFAULT 'UNIT',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    CONSTRAINT uk_uoms_code UNIQUE (code)
);

CREATE INDEX idx_uoms_category ON uoms(category_id);
CREATE INDEX idx_uoms_type ON uoms(uom_type);
CREATE INDEX idx_uoms_active ON uoms(active);

-- Seed standard UoM categories and units
INSERT INTO uom_categories (name) VALUES
('Unit'), ('Length'), ('Weight'), ('Volume'), ('Time'), ('Area'), ('Working Time');

-- Unit category
INSERT INTO uoms (name, code, category_id, factor, is_reference, uom_type)
SELECT 'Units', 'unit', id, 1, TRUE, 'UNIT' FROM uom_categories WHERE name = 'Unit';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Dozens', 'dozen', id, 12, 'UNIT' FROM uom_categories WHERE name = 'Unit';

-- Length category
INSERT INTO uoms (name, code, category_id, factor, is_reference, uom_type)
SELECT 'Meters', 'm', id, 1, TRUE, 'LENGTH' FROM uom_categories WHERE name = 'Length';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Kilometers', 'km', id, 1000, 'LENGTH' FROM uom_categories WHERE name = 'Length';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Feet', 'ft', id, 0.3048, 'LENGTH' FROM uom_categories WHERE name = 'Length';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Inches', 'in', id, 0.0254, 'LENGTH' FROM uom_categories WHERE name = 'Length';

-- Weight category
INSERT INTO uoms (name, code, category_id, factor, is_reference, uom_type)
SELECT 'Kilograms', 'kg', id, 1, TRUE, 'WEIGHT' FROM uom_categories WHERE name = 'Weight';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Grams', 'g', id, 0.001, 'WEIGHT' FROM uom_categories WHERE name = 'Weight';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Pounds', 'lb', id, 0.453592, 'WEIGHT' FROM uom_categories WHERE name = 'Weight';

-- Volume category
INSERT INTO uoms (name, code, category_id, factor, is_reference, uom_type)
SELECT 'Liters', 'L', id, 1, TRUE, 'VOLUME' FROM uom_categories WHERE name = 'Volume';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Milliliters', 'mL', id, 0.001, 'VOLUME' FROM uom_categories WHERE name = 'Volume';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Gallons', 'gal', id, 3.78541, 'VOLUME' FROM uom_categories WHERE name = 'Volume';

-- Time category
INSERT INTO uoms (name, code, category_id, factor, is_reference, uom_type)
SELECT 'Hours', 'hr', id, 1, TRUE, 'TIME' FROM uom_categories WHERE name = 'Time';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Days', 'day', id, 24, 'TIME' FROM uom_categories WHERE name = 'Time';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Minutes', 'min', id, 0.016667, 'TIME' FROM uom_categories WHERE name = 'Time';

-- Working Time category
INSERT INTO uoms (name, code, category_id, factor, is_reference, uom_type)
SELECT 'Working Hours', 'hr_work', id, 1, TRUE, 'WORKING_HOURS' FROM uom_categories WHERE name = 'Working Time';
INSERT INTO uoms (name, code, category_id, factor, uom_type)
SELECT 'Working Days', 'day_work', id, 8, 'WORKING_HOURS' FROM uom_categories WHERE name = 'Working Time';

COMMENT ON TABLE uom_categories IS 'Groups units of measure (Odoo: uom.category)';
COMMENT ON TABLE uoms IS 'Units of measure with conversion factors (Odoo: uom.uom)';
