-- V26__bank_statements.sql
-- Bank Statement and Bank Statement Line tables (Odoo: account.bank.statement, account.bank.statement.line)

CREATE TABLE bank_statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    reference VARCHAR(100),
    journal_id BIGINT NOT NULL REFERENCES journals(id),
    bank_account_id BIGINT REFERENCES accounts(id),
    state VARCHAR(15) NOT NULL DEFAULT 'DRAFT',
    balance_start NUMERIC(15,2) NOT NULL DEFAULT 0,
    balance_end_real NUMERIC(15,2),
    balance_end NUMERIC(15,2) NOT NULL DEFAULT 0,
    difference NUMERIC(15,2) DEFAULT 0,
    date DATE,
    date_done DATE,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    CONSTRAINT uk_bank_statements_name UNIQUE (name)
);

CREATE INDEX idx_bank_statements_journal ON bank_statements(journal_id);
CREATE INDEX idx_bank_statements_state ON bank_statements(state);
CREATE INDEX idx_bank_statements_date ON bank_statements(date);

CREATE TABLE bank_statement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id BIGINT NOT NULL REFERENCES bank_statements(id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL,
    date DATE NOT NULL,
    description VARCHAR(500),
    payment_reference VARCHAR(100),
    partner_id BIGINT,
    partner_name VARCHAR(255),
    amount NUMERIC(15,2) NOT NULL,
    account_id BIGINT REFERENCES accounts(id),
    counterpart_account_id BIGINT REFERENCES accounts(id),
    move_id BIGINT REFERENCES moves(id),
    is_reconciled BOOLEAN NOT NULL DEFAULT FALSE,
    import_id VARCHAR(100),
    transaction_type VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_bank_statement_lines_statement ON bank_statement_lines(statement_id);
CREATE INDEX idx_bank_statement_lines_reconciled ON bank_statement_lines(statement_id, is_reconciled);
CREATE INDEX idx_bank_statement_lines_partner ON bank_statement_lines(partner_id);
CREATE INDEX idx_bank_statement_lines_import ON bank_statement_lines(import_id);

COMMENT ON TABLE bank_statements IS 'Bank statements for reconciliation workflow (Odoo: account.bank.statement)';
COMMENT ON TABLE bank_statement_lines IS 'Individual transactions on a bank statement (Odoo: account.bank.statement.line)';
