-- V27__analytic_accounting.sql
-- Analytic Accounting tables (Odoo: account.analytic.account, account.analytic.line, account.analytic.plan, account.analytic.distribution.model)

CREATE TABLE analytic_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    company_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    CONSTRAINT uk_analytic_plans_name UNIQUE (name)
);

CREATE TABLE analytic_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(32),
    plan_id BIGINT REFERENCES analytic_plans(id),
    parent_id BIGINT REFERENCES analytic_accounts(id),
    account_type VARCHAR(20) NOT NULL DEFAULT 'EXPENSE',
    partner_id BIGINT,
    project_id BIGINT,
    company_id BIGINT,
    currency_id BIGINT,
    group_id BIGINT,
    tag_ids TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    minimum_balance NUMERIC(15,2),
    balance NUMERIC(15,2) DEFAULT 0,
    total_debit NUMERIC(15,2) DEFAULT 0,
    total_credit NUMERIC(15,2) DEFAULT 0,
    start_date DATE,
    end_date DATE,
    manager_id BIGINT,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    CONSTRAINT uk_analytic_accounts_code UNIQUE (code)
);

CREATE INDEX idx_analytic_accounts_plan ON analytic_accounts(plan_id);
CREATE INDEX idx_analytic_accounts_parent ON analytic_accounts(parent_id);
CREATE INDEX idx_analytic_accounts_type ON analytic_accounts(account_type);
CREATE INDEX idx_analytic_accounts_active ON analytic_accounts(active);

CREATE TABLE analytic_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES analytic_accounts(id),
    date DATE NOT NULL,
    name VARCHAR(500),
    move_line_id BIGINT REFERENCES move_lines(id),
    move_id BIGINT REFERENCES moves(id),
    partner_id BIGINT,
    product_id BIGINT,
    quantity NUMERIC(15,4),
    amount NUMERIC(15,2) NOT NULL,
    amount_currency NUMERIC(15,2),
    currency_id BIGINT,
    product_uom_id BIGINT,
    employee_id BIGINT,
    company_id BIGINT,
    general_account_id BIGINT REFERENCES accounts(id),
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_analytic_lines_account ON analytic_lines(account_id);
CREATE INDEX idx_analytic_lines_date ON analytic_lines(date);
CREATE INDEX idx_analytic_lines_move_line ON analytic_lines(move_line_id);
CREATE INDEX idx_analytic_lines_partner ON analytic_lines(partner_id);

CREATE TABLE analytic_distributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account_id BIGINT REFERENCES analytic_accounts(id),
    destination_account_id BIGINT NOT NULL REFERENCES analytic_accounts(id),
    percentage NUMERIC(5,2) NOT NULL,
    account_type VARCHAR(50),
    journal_id BIGINT REFERENCES journals(id),
    partner_id BIGINT,
    product_id BIGINT,
    company_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_analytic_distributions_source ON analytic_distributions(source_account_id);
CREATE INDEX idx_analytic_distributions_dest ON analytic_distributions(destination_account_id);
CREATE INDEX idx_analytic_distributions_active ON analytic_distributions(active);

-- Seed default analytic plans
INSERT INTO analytic_plans (name, description, active) VALUES
('Departments', 'Track costs by department', TRUE),
('Projects', 'Track costs by project', TRUE),
('Regions', 'Track costs by geographic region', TRUE);

COMMENT ON TABLE analytic_plans IS 'Groups analytic accounts by dimension (Odoo: account.analytic.plan)';
COMMENT ON TABLE analytic_accounts IS 'Analytic accounts for cost/revenue tracking (Odoo: account.analytic.account)';
COMMENT ON TABLE analytic_lines IS 'Individual analytic entries (Odoo: account.analytic.line)';
COMMENT ON TABLE analytic_distributions IS 'Rules for distributing analytic costs (Odoo: account.analytic.distribution.model)';
