-- V28__reconcile_models.sql
-- Reconcile Models for automated bank reconciliation (Odoo: account.reconcile.model, account.reconcile.model.line)

CREATE TABLE reconcile_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    journal_id BIGINT REFERENCES journals(id),
    rule_type VARCHAR(20) NOT NULL DEFAULT 'WRITEOFF_BUTTON',
    match_partner_name BOOLEAN,
    match_label VARCHAR(200),
    match_label_regex VARCHAR(200),
    match_notes TEXT,
    match_notes_regex VARCHAR(200),
    amount_min NUMERIC(15,2),
    amount_max NUMERIC(15,2),
    require_partner BOOLEAN,
    require_same_amount BOOLEAN,
    auto_reconcile BOOLEAN DEFAULT FALSE,
    sequence INTEGER NOT NULL DEFAULT 10,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reconcile_models_journal ON reconcile_models(journal_id);
CREATE INDEX idx_reconcile_models_active ON reconcile_models(active);
CREATE INDEX idx_reconcile_models_sequence ON reconcile_models(sequence);

CREATE TABLE reconcile_model_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL REFERENCES reconcile_models(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES accounts(id),
    label VARCHAR(200),
    amount_type VARCHAR(20) NOT NULL DEFAULT 'FIXED',
    amount NUMERIC(15,2),
    side VARCHAR(10) NOT NULL DEFAULT 'DEBIT',
    tax_id BIGINT REFERENCES taxes(id),
    sequence INTEGER NOT NULL DEFAULT 10
);

CREATE INDEX idx_reconcile_model_lines_model ON reconcile_model_lines(model_id);

COMMENT ON TABLE reconcile_models IS 'Automated bank reconciliation rules (Odoo: account.reconcile.model)';
COMMENT ON TABLE reconcile_model_lines IS 'Accounting entries created by reconcile models (Odoo: account.reconcile.model.line)';
