-- V30__helpdesk_ratings_timesheets.sql
-- Ticket Ratings and Helpdesk Timesheets (Odoo: helpdesk.ticket.rating, helpdesk.timesheet)

CREATE TABLE helpdesk_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES helpdesk_tickets(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    customer_id BIGINT,
    customer_name VARCHAR(255),
    via_email BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_helpdesk_ratings_ticket ON helpdesk_ratings(ticket_id);
CREATE INDEX idx_helpdesk_ratings_customer ON helpdesk_ratings(customer_id);

CREATE TABLE helpdesk_timesheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES helpdesk_tickets(id) ON DELETE CASCADE,
    employee_id BIGINT,
    employee_name VARCHAR(255),
    date DATE NOT NULL,
    description VARCHAR(500),
    unit_amount NUMERIC(10,2) NOT NULL,
    is_billable BOOLEAN NOT NULL DEFAULT TRUE,
    so_line_id BIGINT,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE INDEX idx_helpdesk_timesheets_ticket ON helpdesk_timesheets(ticket_id);
CREATE INDEX idx_helpdesk_timesheets_employee ON helpdesk_timesheets(employee_id);
CREATE INDEX idx_helpdesk_timesheets_date ON helpdesk_timesheets(date);
CREATE INDEX idx_helpdesk_timesheets_billable ON helpdesk_timesheets(is_billable);

COMMENT ON TABLE helpdesk_ratings IS 'Customer satisfaction ratings for tickets (Odoo: helpdesk.ticket.rating)';
COMMENT ON TABLE helpdesk_timesheets IS 'Time tracking on helpdesk tickets (Odoo: helpdesk.timesheet)';
