-- V31__payment_providers_transactions.sql
-- Payment Providers and Transactions (Odoo: payment.provider, payment.transaction)

CREATE TABLE IF NOT EXISTS payment_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    state VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    api_url VARCHAR(500),
    public_key VARCHAR(500),
    secret_key VARCHAR(500),
    webhook_secret VARCHAR(500),
    supported_currencies VARCHAR(200),
    capture_manually BOOLEAN DEFAULT FALSE,
    fee_percentage NUMERIC(5,2),
    fee_fixed NUMERIC(10,2),
    return_url VARCHAR(500),
    cancel_url VARCHAR(500),
    logo_url VARCHAR(500),
    description VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES payment_providers(id) ON DELETE RESTRICT,
    reference VARCHAR(100) NOT NULL UNIQUE,
    amount NUMERIC(12,2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    payment_method_type VARCHAR(50),
    provider_reference VARCHAR(200),
    card_last_digits VARCHAR(4),
    card_brand VARCHAR(50),
    partner_id BIGINT,
    partner_email VARCHAR(255),
    invoice_id BIGINT,
    sale_order_id BIGINT,
    is_capture BOOLEAN DEFAULT FALSE,
    source_transaction_id BIGINT REFERENCES payment_transactions(id),
    provider_message VARCHAR(1000),
    fees_amount NUMERIC(10,2),
    settlement_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payment_tx_provider ON payment_transactions(provider_id);
CREATE INDEX IF NOT EXISTS idx_payment_tx_reference ON payment_transactions(reference);
CREATE INDEX IF NOT EXISTS idx_payment_tx_partner ON payment_transactions(partner_id);
CREATE INDEX IF NOT EXISTS idx_payment_tx_state ON payment_transactions(state);
CREATE INDEX IF NOT EXISTS idx_payment_tx_invoice ON payment_transactions(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payment_tx_sale_order ON payment_transactions(sale_order_id);

COMMENT ON TABLE payment_providers IS 'Payment gateway configurations (Odoo: payment.provider)';
COMMENT ON TABLE payment_transactions IS 'Individual payment attempts (Odoo: payment.transaction)';
