-- V32__crm_leads_stages.sql
-- CRM Leads and Pipeline Stages (Odoo: crm.lead, crm.stage)

CREATE TABLE crm_lead_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 0,
    is_won BOOLEAN DEFAULT FALSE,
    is_folded BOOLEAN DEFAULT FALSE,
    email_template_id BIGINT,
    team_id BIGINT,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE crm_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'LEAD',
    stage VARCHAR(50) DEFAULT 'NEW',
    priority VARCHAR(1) DEFAULT '0',
    expected_revenue NUMERIC(12,2),
    probability NUMERIC(5,2),
    expected_closing DATE,
    partner_id BIGINT,
    partner_name VARCHAR(255),
    contact_name VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    company_name VARCHAR(255),
    source VARCHAR(100),
    medium VARCHAR(100),
    campaign VARCHAR(200),
    user_id BIGINT,
    user_name VARCHAR(255),
    team_id BIGINT,
    team_name VARCHAR(255),
    country_id BIGINT,
    description TEXT,
    converted_at TIMESTAMP,
    converted_to_order_id BIGINT,
    lost_reason VARCHAR(500),
    lost_at TIMESTAMP,
    tags VARCHAR(500),
    activity_date DATE,
    activity_summary VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE INDEX idx_crm_leads_type ON crm_leads(type);
CREATE INDEX idx_crm_leads_stage ON crm_leads(stage);
CREATE INDEX idx_crm_leads_user ON crm_leads(user_id);
CREATE INDEX idx_crm_leads_team ON crm_leads(team_id);
CREATE INDEX idx_crm_leads_partner ON crm_leads(partner_id);
CREATE INDEX idx_crm_leads_source ON crm_leads(source);
CREATE INDEX idx_crm_leads_expected_closing ON crm_leads(expected_closing);
CREATE INDEX idx_crm_leads_activity_date ON crm_leads(activity_date);

COMMENT ON TABLE crm_lead_stages IS 'Pipeline stage configuration (Odoo: crm.stage)';
COMMENT ON TABLE crm_leads IS 'CRM leads and opportunities (Odoo: crm.lead)';
