-- V33__helpdesk_email_gateway.sql
-- Helpdesk Email Gateway (Odoo: mail.alias, helpdesk.team, incoming mail)
-- Enhances existing helpdesk_teams table + creates new tables for aliases and incoming emails.

-- Add email gateway columns to existing helpdesk_teams table
DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN alias_name VARCHAR(100);
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column alias_name already exists'; END $$;

DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN alias_domain VARCHAR(200);
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column alias_domain already exists'; END $$;

DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN use_alias BOOLEAN DEFAULT FALSE;
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column use_alias already exists'; END $$;

DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN default_stage VARCHAR(50);
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column default_stage already exists'; END $$;

DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN team_lead_id BIGINT;
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column team_lead_id already exists'; END $$;

DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN team_lead_name VARCHAR(255);
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column team_lead_name already exists'; END $$;

DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN default_priority VARCHAR(1) DEFAULT '0';
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column default_priority already exists'; END $$;

DO $$ BEGIN
    ALTER TABLE helpdesk_teams ADD COLUMN auto_assign BOOLEAN DEFAULT FALSE;
EXCEPTION WHEN duplicate_column THEN RAISE NOTICE 'column auto_assign already exists'; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_helpdesk_teams_alias ON helpdesk_teams(alias_name) WHERE alias_name IS NOT NULL;

-- New tables
CREATE TABLE IF NOT EXISTS email_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_local_part VARCHAR(100) NOT NULL,
    alias_domain VARCHAR(200),
    full_alias VARCHAR(300) UNIQUE,
    model_type VARCHAR(50) NOT NULL,
    alias_defaults TEXT,
    alias_contact VARCHAR(20) DEFAULT 'ANYONE',
    team_id BIGINT REFERENCES helpdesk_teams(id) ON DELETE SET NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS incoming_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(500),
    in_reply_to VARCHAR(500),
    references_header TEXT,
    from_address VARCHAR(255),
    from_name VARCHAR(255),
    to_addresses VARCHAR(1000),
    cc_addresses VARCHAR(1000),
    subject VARCHAR(500),
    body_text TEXT,
    body_html TEXT,
    raw_headers TEXT,
    received_at TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    matched_alias_id BIGINT REFERENCES email_aliases(id),
    related_ticket_id BIGINT REFERENCES helpdesk_tickets(id),
    reply_to_ticket_id BIGINT REFERENCES helpdesk_tickets(id),
    error_message VARCHAR(1000),
    processed_at TIMESTAMP,
    source VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_incoming_emails_status ON incoming_emails(status);
CREATE INDEX IF NOT EXISTS idx_incoming_emails_from ON incoming_emails(from_address);
CREATE INDEX IF NOT EXISTS idx_incoming_emails_ticket ON incoming_emails(related_ticket_id);
CREATE INDEX IF NOT EXISTS idx_incoming_emails_reply ON incoming_emails(reply_to_ticket_id);
CREATE INDEX IF NOT EXISTS idx_incoming_emails_message_id ON incoming_emails(message_id);
CREATE INDEX IF NOT EXISTS idx_email_aliases_model ON email_aliases(model_type);
CREATE INDEX IF NOT EXISTS idx_email_aliases_team ON email_aliases(team_id);

COMMENT ON TABLE email_aliases IS 'Configurable email addresses that create records (Odoo: mail.alias)';
COMMENT ON TABLE incoming_emails IS 'Raw incoming emails before processing (Odoo: mail.message inbound)';
